#version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      # Nginx sẽ nhận request từ bên ngoài tại port 8080
      - "8080:8080"
    volumes:
      # Map file cấu hình nginx vào trong container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: always
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws:ro
      - ~/.ssh/nguyenp-key-pair.pem:/root/.ssh/nguyenp-key-pair.pem:ro
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  jenkins-data:
  n8n-data: