---
- hosts: all
  become: yes
  vars:
    nagios_server_ip: "44.204.24.61"

  tasks:
    # --- PHẦN 1: CÀI ĐẶT MAIL SERVER (POSTFIX) ---
    - name: Cài đặt Postfix không cần hỏi
      shell: |
        debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)"
        debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
        apt-get install -y postfix
      args:
        warn: no
      changed_when: true

    - name: Đảm bảo dịch vụ Postfix đang chạy
      service:
        name: postfix
        state: started
        enabled: yes

    # --- PHẦN 2: CÀI ĐẶT NAGIOS CLIENT (NRPE) ---
    - name: Cài đặt Nagios client (NRPE) và các plugin
      apt:
        name:
          - nagios-nrpe-server
          - nagios-plugins
        state: present
        update_cache: yes

    - name: Cấu hình NRPE để cho phép Nagios Server kết nối
      template:
        src: templates/nrpe.cfg.j2
        dest: /etc/nagios/nrpe.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart NRPE

    # ==========================================================
    # CẬP NHẬT: TẠO USER 'newcust'
    # ==========================================================
    - name: Tạo user 'newcust'
      ansible.builtin.user:
        name: newcust
        password: "$6$rounds=656000$yIZ4CcsgYyP.9T6C$7n2eDFOajY9pKN2vK4xEX3a/S4/DAB4PxjS9NlT2e2e9tJFrbU8bJ3UuJEqbexj3b2n8ZkksoWvjTYP745b.I/"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Thêm user 'newcust' vào nhóm sudo
      ansible.builtin.user:
        name: newcust
        groups: sudo
        append: yes

    # --- PHẦN 4: CHO PHÉP ĐĂNG NHẬP SSH BẰNG MẬT KHẨU ---
    - name: Cho phép xác thực SSH bằng mật khẩu
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
        backup: yes
      notify: Restart sshd
    - name: Force restart sshd to apply changes
  service:
    name: sshd
    state: restarted

  handlers:
    - name: Restart NRPE
      service:
        name: nagios-nrpe-server
        state: restarted

    - name: Restart sshd
      service:
        name: sshd
        state: restarted