---
- hosts: all
  become: yes
  vars:
    nagios_server_ip: "44.204.24.61"

  tasks:
    # ====================================================================
    # SỬA LỖI CUỐI CÙNG: CHỈ ĐỊNH DÙNG BASH EXECUTABLE
    # ====================================================================
    - name: Cài đặt Postfix không cần hỏi
      shell:
        # Giữ nguyên các lệnh shell
        cmd: |
          debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)"
          debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
          apt-get install -y postfix
        # THÊM VÀO: Ra lệnh cho Ansible chạy các lệnh trên bằng /bin/bash
        executable: /bin/bash
      changed_when: true

    - name: Đảm bảo dịch vụ Postfix đang chạy
      service:
        name: postfix
        state: started
        enabled: yes

    - name: Cài đặt Nagios client (NRPE) và các plugin
      apt:
        name:
          - nagios-nrpe-server
          - nagios-plugins
        state: present
        update_cache: yes

    - name: Cấu hình NRPE để cho phép Nagios Server kết nối
      template:
        src: templates/nrpe.cfg.j2
        dest: /etc/nagios/nrpe.cfg
      notify: Restart NRPE

    - name: Tạo user 'newcust'
      ansible.builtin.user:
        name: newcust
        password: "$6$rounds=656000$yIZ4CcsgYyP.9T6C$7n2eDFOajY9pKN2vK4xEX3a/S4/DAB4PxjS9NlT2e2e9tJFrbU8bJ3UuJEqbexj3b2n8ZkksoWvjTYP745b.I/"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Thêm user 'newcust' vào nhóm sudo
      ansible.builtin.user:
        name: newcust
        groups: sudo
        append: yes

    - name: Xóa file cấu hình SSH của cloud-init để tránh xung đột
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        state: absent
      notify: Restart sshd

  handlers:
    - name: Restart NRPE
      service:
        name: nagios-nrpe-server
        state: restarted

    - name: Restart sshd
      service:
        name: sshd
        state: restarted